<?php

namespace ContactBundle\Repository;

/**
 * ClientsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientsRepository extends \Doctrine\ORM\EntityRepository
{
	public function searchClient($pseudo,$password)
	{

		$query = $this->createQueryBuilder('c');

		$query
			->select('c.id')
			->where('c.pseudo = :pseudo')
			->setParameter('pseudo', $pseudo)
			->andWhere('c.password = :password')
			->setParameter('password', md5($password))
		;

		$query->setMaxResults(1);

		return $query->getQuery()->getResult();
	}

}